language: java

jdk:
  - oraclejdk8
  - oraclejdk7

script:
  mvn -s settings.xml clean install

notifications:
  email:
    recipients:
      - dev@milyn.codehaus.org
    on_success: [change]
    on_failure: [always]
